### PR TITLE
Wopiserver Cleared - Flake8 E501 and W503 ignored (Lint)

### PR DESCRIPTION
**Pull request by osamaahmed17**
Managed to clear the error by Flake8 for Wopiserver. Ignored the following error as they are for line length or deprecated
E501: Line too long (82 &gt; 79 characters) 
W503: Line break occurred before a binary operator. Check here for its deprecation (https://github.com/mila-iqia/cookiecutter-pyml/issues/10)

### CODE REVIEW

**Review by glpatcern — APPROVED** [review]

**Comment by osamaahmed17** [comment]
I have **cleared** all the Lint issues in the Wopiserver Project. Was having a merge conflict which I cleared. Hopefully, it's ready to get merged after reviewing from @glpatcern. Do **mention** when it is **ready** to marked "**Ready for review"**.

**Comment by osamaahmed17** [comment]
While going through the code, these commits to the Master branch were added later. That's why it's showing a conflict, I guess.

**Review by glpatcern — CHANGES_REQUESTED** [review]
Hello Osama, thanks for this contribution. As mentioned earlier, a few changes need to be reverted or slightly amended so to make sense: after all, linting should help readability, not hinder it. Therefore, please go through the suggestions (you can mark yourself the PR as ready for review once this is done).

For the few conflicts, this is because the project moves forward ;-) anyway they look rather trivial to fix.

**Comment by glpatcern** [comment]
Once fixed and merged, this closes #60: the linting so far is more than sufficient, as we got rid of some python 2 remainings. The line length is an open debate: GitHub is configured with 127 chars, we have further relaxed it to 130 chars and there are just a few lines longer than that, that's totally fine. Honestly I don't think that nowadays any developer uses 79 chars as a maximum line length.

**Comment by osamaahmed17** [comment]
> Once fixed and merged, this closes #60: the linting so far is more than sufficient, as we got rid of some python 2 remainings. The line length is an open debate: GitHub is configured with 127 chars, we have further relaxed it to 130 chars and there are just a few lines longer than that, that's totally fine. Honestly I don't think that nowadays any developer uses 79 chars as a maximum line length.

Yeah its still a mystery 😄

**Comment by osamaahmed17** [comment]
Resolved conflicts. Have accepted all the changes from master in my branch.

**Review by glpatcern — APPROVED** [review]
With the additional fixes I have pushed, this is now OK to merge

**Pull request merged**
